CREATE DATABASE IF NOT EXISTS crudapp;
USE crudapp;

CREATE TABLE IF NOT EXISTS items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  quantity INT NOT NULL
);

CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'FAVCP9B3UE!sdf';
GRANT ALL PRIVILEGES ON crudapp.* TO 'app'@'%';
FLUSH PRIVILEGES;

